### ISSUE TITLE
py3.6+ torch1.0

### ISSUE THREAD

**Issue by Guojing6** [ShomyLiu/Neu-Review-Rec#7]
报这个BUG 有人遇到过吗

Traceback (most recent call last):
     File "/home/ubuntu/MyFiles/Neu-Review-Rec-master/main.py", line 186, in <module>
                    train()
File "/home/ubuntu/MyFiles/Neu-Review-Rec-master/main.py", line 108, in train
                 mse loss = mse func(output, scores) 
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 489, in call 
                   result = self. forward(*input, **kwaras) 
File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", Line 435, in forward 
          return F.mse loss(input, target, reduction=self.reduction) 
File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", Line 2156, in mse Loss
          ret = torch. C. nn.mse loss(expanded input, expanded target, Reduction.get enum(reduction)) 
RuntimeError: reduce failed to synchronize: device-side assert kriqqeredProcess finished with exit code 1

**Comment by ShomyLiu** [comment]
你好，我这边无法复现这个问题。建议检查下环境，比如cuda是否可以正常使用。
